import './globals.css';
import * as React from 'react';
import type { Metadata, ResolvingMetadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from './Providers';
import { dir } from 'i18next';
import Toolbar from '@mui/material/Toolbar';
import { initTranslations } from '@i18n/index';
import { DictionaryLang, WebsiteLang } from '../../api/types.model';
import TopBar from './components/TopBar';
import { colors } from './colors';

const languages = ['eng', 'rus', 'lez'];

export async function generateStaticParams() {
  return languages.map((lang) => ({ lang }));
}

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Gafargan dictionary',
//   description: 'Generated by create next app',
// };

export async function generateMetadata(
  props: RootLayoutProps,
  parent: ResolvingMetadata,
): Promise<Metadata> {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const { t } = await initTranslations(props.params.lang);
  return {
    title: t('meta.title'),
    description: t('meta.description'),
    // openGraph: {
    //   images: ['/some-specific-page-image.jpg', ...previousImages],
    // },
  };
}

type RootLayoutProps = {
  children: React.ReactNode;
  params: { lang: string };
  searchParams: { fromLang: string; toLang: string };
};

export default async function RootLayout(props: RootLayoutProps) {
  const {
    children,
    params: { lang },
    // searchParams,
  } = props;
  const { t } = await initTranslations(lang);
  return (
    <html
      lang={lang}
      dir={dir(lang)}
      style={{ scrollBehavior: 'smooth', scrollPaddingTop: '100px' }}
    >
      <body className={inter.className} style={{ backgroundColor: colors.background, margin: 0 }}>
        <Providers locale={lang}>
          <TopBar
            currentLang={lang as WebsiteLang}
            // webLangs={t('languages', { returnObjects: true }) as Record<WebsiteLang, string>}
            // dictLangs={t('languages', { returnObjects: true }) as Record<DictionaryLang, string>}
            // searchLabel={t('search')}
          />
          {/* <Toolbar sx={{ p: '10px' }} /> */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
