import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './Providers';
import { dir } from 'i18next'

const languages = ['eng', 'rus', 'lez']

export async function generateStaticParams() {
  return languages.map((lang) => ({ lang }))
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gafargan dictionary',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: {
    lang
  }
}: {
  children: React.ReactNode,
  params: {
    lang: string
  }
}) {
  return (
    <html lang={lang} dir={dir(lang)}>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
