-- Reset all identity columns in the database to 1

TRUNCATE TABLE history_definition RESTART IDENTITY CASCADE;
TRUNCATE TABLE history_source RESTART IDENTITY CASCADE;
TRUNCATE TABLE history_spelling_variant RESTART IDENTITY CASCADE;
TRUNCATE TABLE history_translations RESTART IDENTITY CASCADE;
TRUNCATE TABLE history_word RESTART IDENTITY CASCADE;
TRUNCATE TABLE history_word_details RESTART IDENTITY CASCADE;
TRUNCATE TABLE history_definition_example CASCADE;
TRUNCATE TABLE history_word_details_example CASCADE;

TRUNCATE TABLE definition_example CASCADE;
TRUNCATE TABLE word_details_example CASCADE;
TRUNCATE TABLE translations RESTART IDENTITY CASCADE;
TRUNCATE TABLE definition RESTART IDENTITY CASCADE;
TRUNCATE TABLE word_details RESTART IDENTITY CASCADE;
TRUNCATE TABLE spelling_variant RESTART IDENTITY CASCADE;
TRUNCATE TABLE word RESTART IDENTITY CASCADE;
TRUNCATE TABLE "source" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "user" RESTART IDENTITY CASCADE;
TRUNCATE TABLE lang_dialect RESTART IDENTITY CASCADE;